### ISSUE TITLE
Minor Layout Issues with Return to Top button

### ISSUE THREAD

**Issue by LiamInJapan** [BlackrockDigital/startbootstrap-freelancer-jekyll#5]
Tested in small browser window on Chrome, mobile mode on Chrome's dev mode, and also on iPhone 5C. 

The Chevron seems to be out of place on the "return to top" button. Also as it's exactly the same colour as the footer, it gets drowned out when scrolling.

<img width="903" alt="screen shot 2016-06-27 at 17 28 03" src="https://cloud.githubusercontent.com/assets/1658103/16373493/8b6b84b4-3c8d-11e6-8d6b-3a76a1fdde27.png">

**Comment by davidtmiller** [comment]
Might change this in a future release, but it's not big enough of a problem to warrant a bunch of time unfortunately.
